### ISSUE TITLE
NoSuchMethodError: method not found: '<'

### ISSUE THREAD

**Issue by darkoverlordofdata** [playif/play_phaser#12]
I started seeing this error on the console log when I upgraded to 11.0 - I see it in 11.1 as well.
Class Menu extends the Phaser.State class. The log entry shows up when I click on a Phaser.Button object. Nothing seems broken, the behavior is working, it just logs exceptions.

Exception: Class 'Menu' has no instance method '<'.

NoSuchMethodError: method not found: '<'
Receiver: Instance of 'Menu'
Arguments: [1] package:play_phaser/gameobjects/image.dart:896Image.set:frame package:play_phaser/gameobjects/image.dart:896Button.setState package:play_phaser/gameobjects/button.dart:574Button.onInputOverHandler package:play_phaser/gameobjects/button.dart:450SignalBinding.execute package:play_phaser/core/signal_binding.dart:40Signal.dispatch package:play_phaser/core/core_signal.dart:160InputHandler._pointerOverHandler@290914109 package:play_phaser/input/input_handler.dart:818Pointer.processInteractiveObjects package:play_phaser/input/pointer.dart:652Pointer.move package:play_phaser/input/pointer.dart:526Mouse.onMouseMove package:play_phaser/input/mouse.dart:397Mouse.<anonymous closure> package:play_phaser/input/mouse.dart:301
Exception: Class 'Menu' has no instance method '<'.

NoSuchMethodError: method not found: '<'
Receiver: Instance of 'Menu'
Arguments: [1]
